-- ============================================================
-- 005: Alerts — generated by nightly portfolio monitor
-- P2 feature, but schema should exist from day 1
-- ============================================================

CREATE TYPE alert_type AS ENUM (
  'compliance_change',    -- unit went from compliant → non-compliant (or vice versa)
  'rent_gap_change',      -- predicted rent changed significantly
  'market_drift',         -- neighborhood-level market movement
  'mieterhoehung_eligible' -- unit is eligible for §558 rent increase
);

CREATE TABLE IF NOT EXISTS public.alerts (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  unit_id      UUID REFERENCES public.units(id) ON DELETE CASCADE,  -- nullable for portfolio-level alerts

  type         alert_type NOT NULL,
  title        TEXT NOT NULL,          -- e.g. "Compliance status changed"
  message      TEXT NOT NULL,          -- e.g. "Unit 'Kreuzberg Altbau' is now above legal max by €1.20/m²"
  severity     TEXT NOT NULL DEFAULT 'info' CHECK (severity IN ('info', 'warning', 'critical')),

  -- Context data (varies by alert type)
  data         JSONB,                  -- e.g. { old_status: "compliant", new_status: "non_compliant", delta: 1.20 }

  is_dismissed BOOLEAN NOT NULL DEFAULT false,
  dismissed_at TIMESTAMPTZ,

  detected_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_alerts_user_active ON public.alerts(user_id, detected_at DESC)
  WHERE is_dismissed = false;
CREATE INDEX idx_alerts_unit ON public.alerts(unit_id, detected_at DESC);

-- RLS
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own alerts"
  ON public.alerts FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can update own alerts"
  ON public.alerts FOR UPDATE
  USING (auth.uid() = user_id);
